language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -q -e . --use-mirrors
script:
  - python setup.py test
deploy:
  provider: openshift
  user: nemesiscodex
  password:
    secure: D4/BZJ0S/VfVUMgMigAw3KqECmXS+Ztusg3beD1QAlc0GjYpkgEmiHfhEaolon/VSX9n17KAYFMkk4ug84PSb7mUpSQEreqWfB+a/uw52xwFQzWNrxddyysL16euNQNFlojjKTFHGJwfQQ374hlVk/cuvfjIutDJO945AdG9j0I=
  app: mecmapi
  domain: master
  on:
    repo: nemesiscodex/openfonacide
    branch: master
